evaluation:
  eval_model: llada-8b
  tasks: "math500_reasoning"
  num_fewshot: 4
  batch_size: 8
  seed: 42
  device: "cuda"
  apply_chat_template: False

  model_args:
    pretrained: "GSAI-ML/LLaDA-8B-Base"
    dtype: "bfloat16"
    max_new_tokens: 512
    steps: 256
    block_size: 32
    temperature: 0.0
