evaluation:
  # Evaluation Harness
  script_path: "dllm/pipelines/llada/eval.py"
  tasks: "math500_reasoning"
  num_fewshot: 4
  batch_size: 8
  seed: 42
  device: "cuda"
  apply_chat_template: False   
  log_samples: True

  # Model Configuration
  model: "llada"
  model_args:
    pretrained: ".models/LLaDA-8B-Base/tulu-3-sft-mixture/base/lr2e-05_bs128/checkpoint-final" # "GSAI-ML/LLaDA-8B-Base"
    dtype: "bfloat16"
    
    # Interventions (Disabled)
    use_cab: False
    use_loopholing: False
    lora: False
    merge_lora: False
    
    # Sampling Strategy 
    max_new_tokens: 512
    steps: 256          
    block_size: 32
    temperature: 0.0    
    remasking: "low_confidence"
    threshold: 0.0      
