evaluation:
  tasks: "math500_reasoning"
  num_fewshot: 4
  
  model_args:
    pretrained: ".models/LLaDA-8B-Base/NuminaMath-CoT-LLaDA-Goldilocks/base-puma-bptt-cab/lr2e-05_bs256_puma-th0.15_bptt2_cab-b1024-e2048-rl17/checkpoint-200"
    
    use_cab: True
    cab_size: small
    read_layers: 18 # base 1
    injection: mask

    use_loopholing: True
    threshold: 0.15
