evaluation:
  tasks: "math500_reasoning"
  num_fewshot: 4
  
  model_args:
    pretrained: ".models/LLaDA-8B-Base/tulu-3-sft-mixture/base-puma-bptt-cab/lr5e-05_bs256_puma-th0.15_bptt4_cab-b2048-e4096-mask-rl15-30/checkpoint-final"
    
    use_cab: True
    cab_size: large
    read_layers: [[16, 31]] # base 1
    injection: masked

    use_loopholing: True
    threshold: 0.15
