evaluation:
   eval_model: fast-dllm
   tasks: "math500_reasoning"
   apply_chat_template: True
   num_fewshot: 0
   model_args:
     pretrained: "Efficient-Large-Model/Fast_dLLM_v2_1.5B"
     use_loopholing: False
     threshold: 0.0