evaluation:
  seed: 0
  script_path: dllm/pipelines/llada/eval.py
  model: llada
  tasks: math500_reasoning
  batch_size: 1
  device: cuda
  apply_chat_template: false
  num_fewshot: 4
  log_samples: true
  model_args:
    pretrained: .models/llada-lora-puma-bptt/lr2e-5_s42/checkpoint-1000
    dtype: bfloat16
    max_new_tokens: 512
    steps: 512
    block_size: 32
    temperature: 0.7
    threshold: 0.15
    use_loopholing: true
    lora: true
    merge_lora: true
