# Slurm Resource Requests
job_name: "dllm"
nodes: 1
gpus_per_node: "h100:4"
time: "01:00:00"
mem: "40G"
cpus_per_task: 16
ntasks_per_node: 1
output: "./.logs/%x-%j.out"
error: "./.logs/%x-%j.err"
requeue: true
working_dir: "/scratch/jacopo04/dllm"