nodes: 2
gpus_per_node: "h100:1"
time: "01:00:00"
mem: "150G"
cpus_per_task: 32
ntasks_per_node: 1
output: "./.logs/%x-%j.out"
error: "./.logs/%x-%j.err"
requeue: true
working_dir: "/scratch/jacopo04/dllm"
account: "def-rudner"
signal: "B:SIGTERM@660"