training:
  core:
    script_path: "examples/llada/sft.py"
    model_name_or_path: "GSAI-ML/LLaDA-8B-Base"
    bf16: True
    gradient_checkpointing: True
    seed: 42
    ddp_find_unused_parameters: False
    loss_type: "bptt"
  
  bptt:
    active: True
    bptt_steps: 4
  
  lora:
    active: False
    r: 32
    lora_alpha: 64
    lora_dropout: 0.05
    target_modules: "all-linear"
  
  cab:
    active: True
    cab_bottleneck_dim: 512
    cab_mlp_expansion_dim: 1024
  
  hyperparameters:
    num_train_epochs: 3
    learning_rate: 2e-05
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 8
    lr_scheduler_type: "linear"
    warmup_ratio: 0.1
    max_grad_norm: 1.0
  
  dataset:
    dataset_args: "openai/gsm8k[train:7473,test:1319]"
    use_chat_template: False
    mask_prompt_loss: True
  
  logging:
    logging_steps: 10
    save_steps: 50
    eval_steps: 20
    save_only_model: False
