training:
  core:
    model_name_or_path: llada-8b
    loss_type: "puma"
  
  lora:
    active: True
    r: 32
    lora_alpha: 64
  
  puma: { active: True }

  hyperparameters:
    max_steps: 500
    learning_rate: 2e-05
  
  dataset: gsm8k
