training:
  core:
    model_name_or_path: llada-8b
    loss_type: "puma_bptt"
  
  puma: { active: True }
  bptt: 2

  loophole:
    active: True
    read_layers: 16 # base 1
    injection: masked
    mlp_module: True
  
  hyperparameters:
    max_steps: 500
    learning_rate: 2e-05
  
  dataset: tulu
